[project]
name = "profitcli"
version = "1.0.0.dev5"
description = "CLI acessível para Profit DLL"
authors = [
    {name = "Valmir França",email = "vfranca3@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "click (>=8.3.1,<9.0.0)"
]

[project.scripts]
pft = "profitcli.cli:cli"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
